apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  name: gocd-binding
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: gocd
  namespace: ${NAMESPACE}
userNames:
- system:serviceaccount:${NAMESPACE}:gocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.gocd: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"gocd"}}'
  name: gocd
