apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: gocd-ansible-agent
  name: gocd-ansible-agent
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: DockerImage
      name: docker-registry.default.svc:5000/${NAMESPACE}/gocd-ansible-agent:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: gocd-ansible-agent
    git:
      uri: https://github.com/ArctiqTeam/openshift-gocd
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
